### ISSUE TITLE
Absolute path images and cui-req

### ISSUE THREAD

**Issue by hippostar** [acesinc/convergent-ui#10]
I have a backend service returning a HTML fragment which gets included in my page by convergent-ui. The HTML fragment returned contains an image with an absolute path "/portal/img/logo.png" the adress of the image in the fragment gets changed to "/cui-req://http://localhost/portal/img/logo.png" when the fragment is inserted into the page.

Finally, once the page is downloaded, the browser will request "/cui-req://http://localhost/portal/img/logo.png" which will fail with a 404. Its like the cui-req URL doesn't get picked up by the filter.

What did I do wrong?

**Comment by AshlynGraf** [comment]
Example of the configuration used 
[A.txt](https://github.com/acesinc/convergent-ui/files/632403/A.txt)
[B.txt](https://github.com/acesinc/convergent-ui/files/632408/B.txt)

**Comment by andrewserff** [comment]
You uncovered a nasty bug we introduced when we upgraded to spring-cloud Brixton! I believe I have fixed it and am in the process of releasing v1.1.1. Please give that a try when it's available in [maven central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22net.acesinc%22%20AND%20a%3A%22convergent-ui%22).
