### ISSUE TITLE
Current State of Project

### ISSUE THREAD

**Issue by ccit-spence** [acesinc/convergent-ui#4]
Wanted to check and see how this project is progressing.  Is it working to your expectations?  Has it been deployed in production?  

I had posted an issue with the Spring Cloud team at one point looking for something like this for UI.

**Comment by andrewserff** [comment]
Thanks for the interest! We are still using it in our development.  It hasn't been put into production yet, but it's going that way.  We haven't had any issues within our development so far, but it hasn't been stress tested yet, so if you take it further, I'd love to hear about it!  What are your specific concerns?

**Comment by ccit-spence** [comment]
Thanks for the quick response.  I will keep you posted on how it works on our end.  We had seriously thought about the Node version of Composure, I like Spring and didn't want to leave the ecosystem.
