### ISSUE TITLE
Could you please let me know how filter initiates, I was getting error while Filter initialization

### ISSUE THREAD

**Issue by techsynbytes** [acesinc/convergent-ui#8]

**Comment by techsynbytes** [comment]
Could not autowire field: private
java.util.Map org.springframework.cloud.netflix.zuul.ZuulConfiguration$ZuulFilte
rConfiguration.filters; nested exception is org.springframework.beans.factory.Be
anCreationException:

**Comment by andrewserff** [comment]
Could you provide some more info like the full stack trace?  The ConvergentUI filter is a ZuulFilter, so it is registered as a bean and Zuul automatically registers the Filter. Is this error happening on server start or when you try to hit your endpoint?

**Comment by andrewserff** [comment]
This issue is very old so I assume it's no longer an issue.  Closing.
